CREATE TABLE PARENT (
    PRT_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    PRT_FULLNAME VARCHAR2(50) NOT NULL,
    PRT_GENDER CHAR(1) NOT NULL CHECK (PRT_GENDER IN ('M', 'F')),
    PRT_DATE_OF_BIRTH DATE NOT NULL,
    PRT_AGE INT NOT NULL CHECK (PRT_AGE >= 0),
    PRT_CONTACT_NO VARCHAR2(20) NOT NULL,
    PRT_ADDRESS VARCHAR2(255) NOT NULL,
    PRT_EMAIL VARCHAR2(50) NOT NULL CHECK (REGEXP_LIKE(PRT_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')),
    PRT_RACE VARCHAR2(20) NOT NULL,
    RELATIONSHIP_WTH_STD VARCHAR2(20) NOT NULL,
    PRT_JOB VARCHAR2(50)
);

CREATE TABLE STUDENT (
    STUD_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    STUD_FULLNAME VARCHAR2(50) NOT NULL,
    STUD_GENDER CHAR(1) NOT NULL CHECK (STUD_GENDER IN ('M', 'F')),
    STUD_DATE_OF_BIRTH DATE NOT NULL,
    STUD_AGE INT NOT NULL CHECK (STUD_AGE BETWEEN 6 AND 12),
    STUD_RACE VARCHAR2(20) NOT NULL,
    STUD_SCHOOL VARCHAR2(50) NOT NULL,
    PRT_ID VARCHAR2(20) REFERENCES PARENT(PRT_ID)
);

CREATE TABLE PROGRAMME (
    PROG_CODE VARCHAR2(20) PRIMARY KEY NOT NULL,
    PROG_NAME VARCHAR2(50) NOT NULL,
    PROG_TIME VARCHAR2(20) NOT NULL,
    PROG_FEE FLOAT NOT NULL
);

CREATE TABLE REGISTRATION (
    REG_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    STUD_ID VARCHAR2(20) REFERENCES STUDENT(STUD_ID), 
    PROG_CODE VARCHAR2(20) REFERENCES PROGRAMME(PROG_CODE), 
    REG_STATUS VARCHAR2(10) NOT NULL,
    REG_DATE DATE
);

CREATE TABLE GROWTH_RECORD (
    RECORD_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    STUD_ID VARCHAR2(20) REFERENCES STUDENT(STUD_ID),
    CONFIDENCE_LVL INT CHECK (CONFIDENCE_LVL BETWEEN 1 AND 10),
    LEADERSHIP_LVL INT CHECK (LEADERSHIP_LVL BETWEEN 1 AND 10),
    CRIC_THINKING_LVL INT CHECK (CRIC_THINKING_LVL BETWEEN 1 AND 10),
    PROB_SOLVING_LVL INT CHECK (PROB_SOLVING_LVL BETWEEN 1 AND 10),
    COURAGEOUS_LVL INT CHECK (COURAGEOUS_LVL BETWEEN 1 AND 10),
    AREA_OF_IMP VARCHAR2(255)
);

CREATE TABLE DEPARTMENT (
    DEPT_ID VARCHAR(20) PRIMARY KEY NOT NULL,
    DEPT_NAME VARCHAR(50) NOT NULL,
    DEPT_DESC VARCHAR (255) NOT NULL
);

CREATE TABLE COACH (
    CCH_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    CCH_FULLNAME VARCHAR2(50) NOT NULL,
    CCH_GENDER CHAR(1) NOT NULL CHECK (CCH_GENDER IN ('M', 'F')),
    CCH_DATA_OF_BIRTH DATE NOT NULL,
    CCH_AGE INT NOT NULL CHECK (CCH_AGE >= 0),
    CCH_EMAIL VARCHAR2(50) NOT NULL CHECK (REGEXP_LIKE(CCH_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')),
    CCH_CONTACT_NO VARCHAR2(20) NOT NULL,
    CCH_RACE VARCHAR2(20) NOT NULL,
    CCH_ADDRESS VARCHAR2(255) NOT NULL,
    CCH_COACH_NAME VARCHAR2(50) NOT NULL,
    CCH_POSITION VARCHAR2(50) NOT NULL,
    CCH_BANK_NAME VARCHAR2(50) NOT NULL,
    CCH_BANK_ACC_NO VARCHAR2(20) NOT NULL,
    CCH_SALARY FLOAT, 
    DEPT_ID VARCHAR2(20) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE CLASS (
    CLASS_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    CLASS_DATE DATE NOT NULL,
    CLASS_MODULE VARCHAR2(255) NOT NULL,
    CLASS_VALUE VARCHAR2(255) NOT NULL,
    CCH_ID VARCHAR2(20) REFERENCES COACH(CCH_ID)
);

CREATE TABLE STUDENT_INV (
    SINV_NO VARCHAR2(20) PRIMARY KEY NOT NULL,
    SINV_BILL_DATE DATE NOT NULL,
    SINV_DUE_DATE DATE NOT NULL,
    SINV_DESC VARCHAR2(255),
    SINV_AMOUNT FLOAT NOT NULL,
    STUD_ID VARCHAR2(20) REFERENCES STUDENT(STUD_ID), 
    PROG_CODE VARCHAR2(20) REFERENCES PROGRAMME(PROG_CODE),
    CHECK (SINV_DUE_DATE >= SINV_BILL_DATE)
);

CREATE TABLE STUDENT_PAYMENT_DETAILS (
    SPAY_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    SPAY_DATE DATE NOT NULL,
    SPAY_AMOUNT FLOAT NOT NULL,
    SPAY_METHOD VARCHAR2(50) NOT NULL,
    SPAY_PLAN VARCHAR2(20) NOT NULL
);

CREATE TABLE STUDENT_PAYMENT (
    SINV_NO VARCHAR2(20) NOT NULL,
    SPAY_ID VARCHAR2(20),
    PRIMARY KEY (SINV_NO, SPAY_ID),
    FOREIGN KEY (SINV_NO) REFERENCES STUDENT_INV(SINV_NO),
    FOREIGN KEY (SPAY_ID) REFERENCES STUDENT_PAYMENT_DETAILS(SPAY_ID),
    SPAY_STATUS VARCHAR2(20) NOT NULL
);

CREATE TABLE MERCHANDISE (
    MERC_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    MERC_NAME VARCHAR2(50) NOT NULL UNIQUE,
    MERC_DESC VARCHAR2(255),
    MERC_CATE VARCHAR2(50) NOT NULL,
    MERC_PRICE FLOAT NOT NULL,
    MERC_STOCK_QTY INT NOT NULL
);

CREATE TABLE CUSTOMER_DETAILS (
    CUS_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    CUS_NAME VARCHAR2(50) NOT NULL,
    CUS_CONTACT_NO VARCHAR2(20) NOT NULL,
    CUS_EMAIL VARCHAR2(50) CHECK (REGEXP_LIKE(CUS_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'))
);

CREATE TABLE CUSTOMER_ORDER (
    CORDER_REF_NO VARCHAR2(20) PRIMARY KEY NOT NULL,
    CUS_ID VARCHAR2(20) REFERENCES CUSTOMER_DETAILS(CUS_ID),
    CORDER_DATE DATE NOT NULL,
    MERC_ID VARCHAR2(20) REFERENCES MERCHANDISE(MERC_ID),
    CORDER_QTY INT NOT NULL,
    CORDER_AMOUNT FLOAT NOT NULL,
    CCH_ID VARCHAR2(20) REFERENCES COACH(CCH_ID)
);

CREATE TABLE RECEIPT (
    RECEIPT_NO VARCHAR2(20) PRIMARY KEY NOT NULL,
    RECEIPT_DATE DATE NOT NULL,
    RECEIPT_DESC VARCHAR2(255) NOT NULL
);

CREATE TABLE CUSTOMER_PAYMENT (
    CPAY_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    CORDER_REF_NO VARCHAR2(20) REFERENCES CUSTOMER_ORDER(CORDER_REF_NO),
    CPAY_DATE DATE NOT NULL,
    CPAY_METHOD VARCHAR2(50) NOT NULL,
    CPAY_AMOUNT FLOAT NOT NULL,
    RECEIPT_NO VARCHAR2(20) REFERENCES RECEIPT(RECEIPT_NO)
);

CREATE TABLE MANUFACTURER_DETAILS (
    MFR_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    MFR_NAME VARCHAR2(50) NOT NULL,
    MFR_ADDRESS VARCHAR2(255) NOT NULL,
    MFR_PIC VARCHAR2(50) NOT NULL,
    MFR_CONTACT_NO VARCHAR2(20) NOT NULL
);

CREATE TABLE MANUFACTURER_ORDER (
    MORDER_REF_NO VARCHAR2(20) PRIMARY KEY NOT NULL,
    MFR_ID VARCHAR2(20) REFERENCES MANUFACTURER_DETAILS(MFR_ID),
    MERC_ID VARCHAR2(20) REFERENCES MERCHANDISE(MERC_ID),
    MORDER_DATE DATE NOT NULL,
    MORDER_QTY INT NOT NULL,
    MORDER_TOTALCOST FLOAT NOT NULL,
    CCH_ID VARCHAR2(20) REFERENCES COACH(CCH_ID)
);

CREATE TABLE MANUFACTURER_INV (
    MINV_NO VARCHAR2(20) PRIMARY KEY NOT NULL,
    MORDER_REF_NO VARCHAR2(20) REFERENCES MANUFACTURER_ORDER(MORDER_REF_NO),
    MINV_BILL_DATE DATE NOT NULL,
    MINV_DUE_DATE DATE NOT NULL,
    MINV_DESC VARCHAR2(255) NOT NULL,
    MINV_AMOUNT FLOAT NOT NULL
    CONSTRAINT CHK_DUE_DATE CHECK (MINV_DUE_DATE >= MINV_BILL_DATE);
);

CREATE TABLE TRANSACTION (
    TRANS_ID VARCHAR2(20) PRIMARY KEY NOT NULL,
    MINV_NO VARCHAR2(20) REFERENCES MANUFACTURER_INV(MINV_NO),
    TRANS_METHOD VARCHAR2(50) NOT NULL,
    TRANS_AMOUNT FLOAT NOT NULL,
    TRANS_DATE DATE NOT NULL
);

INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0001', 'Ong Ming Heng', 'M', TO_DATE('1980-06-20', 'YYYY-MM-DD'), 43, '01135538789', '12 Jalan Merdeka, Kuala Lumpur', 'mingheng66@gmail.com', 'Chinese', 'Father', 'Engineer');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0002', 'Lee Yan Fang', 'F', TO_DATE('1982-09-15', 'YYYY-MM-DD'), 41, '0198765432', '9B, Lorong Medan Tuanku, Petaling Jaya', 'leeyanfang@gmail.com', 'Chinese', 'Mother', 'Teacher'),
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0003', 'Tan Mei Ling', 'F', TO_DATE('1985-03-08', 'YYYY-MM-DD'), 38, '01154237796', '78, Lorong 5, Jalan Damai, Kuala Lumpur', 'meiling@gmail.com', 'Chinese', 'Mother', 'Shopkeeper');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0004', 'Rajendra Kumar a/l Subramaniam', 'M', TO_DATE('1988-11-12', 'YYYY-MM-DD'), 35, '0187654321', '101 Jalan Sentosa, Kota Damansara', 'rajendra.kumar@gmail.com', 'Indian', 'Father', 'Doctor');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0005', 'Loh Kun Ling', 'F', TO_DATE('1990-05-03', 'YYYY-MM-DD'), 33, '0123986340', '4B, Ken3, Jalan Harmoni, Petaling Jaya', 'ling6694@gmail.com', 'Chinese', 'Mother', 'Designer');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0006', 'Muhammad Ali bin Hassan', 'M', TO_DATE('1978-02-18', 'YYYY-MM-DD'), 45, '0199867239', '88 Jalan Bahagia, Kuala Lumpur', 'muhammad.ali@gmail.com', 'Malay', 'Father', 'Electric Technician');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0007', 'Lavanya Devi a/p Muthusami', 'F', TO_DATE('1983-07-05', 'YYYY-MM-DD'), 40, '0121491235', '3rd Floor, Jalan Raja Chulan, Wisma HLA, Damansara', 'lavanya.devi@gmail.com', 'Indian', 'Mother', 'Lawyer');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0008', 'Lim Wei Shen', 'M', TO_DATE('1987-10-30', 'YYYY-MM-DD'), 36, '0123167981', 'No 18, Lorong Brunai 3, Jalan Pudu, Petaling Jaya', 'weishenlim@gmail.com', 'Chinese', 'Father', 'Business Owner');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0009', 'Tan Thing Thing', 'F', TO_DATE('1981-04-12', 'YYYY-MM-DD'), 42, '0191264322', '5, SS12/2, Jalan Damansara, Kuala Lumpur', 'thing22@gmail.com', 'Chinese', 'Mother', 'IT Consultant');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0010', 'Ahmad bin Mohd Yusof', 'M', TO_DATE('1974-12-03', 'YYYY-MM-DD'), 49, '0135723906', '5B, Ria Ehsan Appartment, Jalan Ria, Kuala Lumpur', 'ahmadyusof@gmail.com', 'Malay', 'Father', 'Dentist');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0011', 'Hong Hui Yin', 'F', TO_DATE('1983-06-25', 'YYYY-MM-DD'), 40, '0122096782', '15-1B, Jalan Pandan 2/2, Pandan Jaya, Damansara', 'huiyinhong@gmail.com', 'Chinese', 'Mother', 'Housewife');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0012', 'Ravi a/l Subramaniam', 'M', TO_DATE('1986-09-08', 'YYYY-MM-DD'), 37, '0187654323', 'Wisma Semantan, 12 Jalan Geligang, Damansara Height', 'ravisubra@gmail.com', 'Indian', 'Father', 'Chef');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0013', 'Aishah binti Ismail', 'F', TO_DATE('1989-03-20', 'YYYY-MM-DD'), 34, '0136750283', '96 Jalan Indah, Damansara', 'aishah89@gmail.com', 'Malay', 'Mother', 'Nurse');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0014', 'Ng Yee Ming', 'M', TO_DATE('1984-08-14', 'YYYY-MM-DD'), 39, '0146290129', 'Wisma Semantan, 12 Jalan Geligang, Damansara Height, Kuala Lumpur', 'yee.ming@gmail.com', 'Chinese', 'Father', 'Marketing Executive');
INSERT INTO PARENT (PRT_ID, PRT_FULLNAME, PRT_GENDER, PRT_DATE_OF_BIRTH, PRT_AGE, PRT_CONTACT_NO, PRT_ADDRESS, PRT_EMAIL, PRT_RACE, RELATIONSHIP_WTH_STD, PRT_JOB)
VALUES('PR0015', 'Yeoh Si Qing', 'F', TO_DATE('1981-01-07', 'YYYY-MM-DD'), 42, '0184028324', '127A, Jalan Aminuddin Baki, Taman Tun Dr. Ismail, Petaling Jaya', 'siqing@gmail.com', 'Chinese', 'Mother', 'Human Resources Manager');

INSERT INTO STUDENT (STUD_ID, STUD_FULLNAME, STUD_GENDER, STUD_DATE_OF_BIRTH, STUD_AGE, STUD_RACE, STUD_SCHOOL, PRT_ID)
VALUES('S0001', 'Ong Xiao Ming', 'M', TO_DATE('2013-05-15', 'YYYY-MM-DD'), 10, 'Chinese', 'SJK (C) Puay Chai', 'PR0001');
INSERT INTO STUDENT (STUD_ID, STUD_FULLNAME, STUD_GENDER, STUD_DATE_OF_BIRTH, STUD_AGE, STUD_RACE, STUD_SCHOOL, PRT_ID)
VALUES('S0002', 'Ong Xiao Mei', 'F', TO_DATE('2016-08-20', 'YYYY-MM-DD'), 7, 'Chinese', 'SJK (C) Puay Chai', 'PR0001');
INSERT INTO STUDENT (STUD_ID, STUD_FULLNAME, STUD_GENDER, STUD_DATE_OF_BIRTH, STUD_AGE, STUD_RACE, STUD_SCHOOL, PRT_ID)
VALUES('S0003', 'Wong Pei Ling', 'M', TO_DATE('2015-03-10', 'YYYY-MM-DD'), 8, 'Chinese', 'SJK(C) Damansara', 'PR0002');



INSERT INTO PROGRAMME (PROG_CODE, PROG_NAME, PROG_TIME, PROG_FEE)
VALUES('AREM001', 'Aumentar''s Route Mastery', '1400-1530', 3880.00);
INSERT INTO PROGRAMME (PROG_CODE, PROG_NAME, PROG_TIME, PROG_FEE)
VALUES('AR003', 'Aumentar''s Route UP~IT', '0930-1100', 4080.00);
INSERT INTO PROGRAMME (PROG_CODE, PROG_NAME, PROG_TIME, PROG_FEE)
VALUES('LPEM001', 'Leader''s Path Mastery', '1400-1600', 3880.00);
INSERT INTO PROGRAMME (PROG_CODE, PROG_NAME, PROG_TIME, PROG_FEE)
VALUES('LP003', 'Leader''s Path UP~IT', '0930-1130', 4080.00);
INSERT INTO PROGRAMME (PROG_CODE, PROG_NAME, PROG_TIME, PROG_FEE)
VALUES('LP004', 'Leader''s Path UP~IT', '1600-1800', 4080.00);
INSERT INTO PROGRAMME (PROG_CODE, PROG_NAME, PROG_TIME, PROG_FEE)
VALUES('MGEM001', 'Mirador''s Guide Mastery', '1400-1530', 3880.00);
INSERT INTO PROGRAMME (PROG_CODE, PROG_NAME, PROG_TIME, PROG_FEE)
VALUES('MG003', 'Mirador''s Guide UP~IT', '0930-1100', 4080.00);

